tcpDump:tcpDump.c
	gcc -o tcpDump tcpDump.c -lpcap
	sudo ./tcpDump en1
testpcap1:
	gcc -Wall -pedantic -o testpcap1 testpcap1.c -lpcap
	sudo ./testpcap1
tackyDump:
	gcc -Wall -pedantic -o tackyDump tackyDump.c -lpcap
	sudo ./tackyDump
tackyDumpp:
	gcc -Wall -pedantic -o tackyDump tackyDump.c -lpcap
	sudo ./tackyDump
